repos:
-   repo: https://github.com/asottile/seed-isort-config
    rev: master
    hooks:
    -   id: seed-isort-config
-   repo: https://github.com/pre-commit/mirrors-isort
    rev: master
    hooks:
    -   id: isort
-   repo: https://github.com/ambv/black
    rev: stable
    hooks:
    - id: black
      args: [--line-length, '80']
      language_version: python3.6
