name: metal
channels:
  - pytorch
  - conda-forge
dependencies: # New core deps should also be added to setup.py for pip
  - python=3.6
  - jupyter
  - matplotlib
  - nb_conda_kernels
  - networkx=2
  - nose
  - numpy
  - pandas
  - pytorch=0.4.1
  - runipy
  - scipy
  - tqdm
