name: metal
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.6
  - jupyter
  - matplotlib=3
  - nb_conda_kernels
  - networkx=2
  - nose
  - numpy
  - pandas
  - pytorch=0.4.1
  - runipy
  - scipy
  - tqdm
